/**
 * @module 系统级常量[CommonConstant]
 * @description  系统级常量
 *
 * @date: 2013-09-17 下午2:42
 */
define([], function () {
    var CommonConstant = {
        //布局中的间距
        Spacing: {
            "DEFAULT": 5,
            "NONE": 0
        },
        ToolBar: {
            "HEIGHT": 36,          //工具栏的高度

            //工具栏在底部时的样式名
            "FOOTER_CONTAINER_CLASS_NAME": " h-toolbar h-toolbar-footer ",  //工具栏在底部时，其归属容器的样式名
            "FOOTER_CLASS_NAME": " h-col h-pull-right "                       //工具栏在底部时，其样式名：右对齐
        },
        //工具栏的位置：顶部、底部
        Position: {
            "TOP": "top",
            "BOTTOM": "bottom"
        },
        Button: {
            "PRIMARY_CLASS_NAME": "h-btn-primary"                //主要按钮的样式名
        },

        /**
         * 标识当前应用功能所处的场景：新增、修改、查看
         */
        Scene: {
            CREATE: "c",            //create
            UPDATE: "u",            //update
            VIEW: "v"               //view
        },
        /**
         * 应用功能的交互模式：浮窗模式、跳转模式、主从模式、批量模式
         */
        Interaction: {
            FLOAT: "float",                   //浮窗模式
            JUMP: "jump",                     //跳转模式
            MASTER_SLAVE: "master_slave",   //主从模式
            "BATCH": "batch"                  //批量模式
        },
        Editor: {
            Type: {}
        },
        //预警的样式效果
        Warning: {
            //行预警的样式
            Row: {
                SUCCESS: "h-bg-success-light",       //成功信息
                INFO: "h-bg-info-light",              //帮助信息
                WARNING: "h-bg-warning-light",       //警示信息
                DANGER: "h-bg-danger-light"          //错误信息
            },
            //列预警的样式
            Column: {
                SUCCESS: "h-color-success h-font-b",   //成功信息
                INFO: "h-color-info h-font-b",          //帮助信息
                WARNING: "h-color-warning h-font-b",   //警示信息
                DANGER: "h-color-danger h-font-b"      //错误信息
            }
        },
        /**
         * 界面上需要用到的各种模版
         */
        Template: {
            //按钮的模版
            Button: {
                "NORMAL": '<a id="<%=id%>" data-act="<%=id%>" class="h-btn <%=className%>" href="javascript:void(0)"><span class="h-btn-content"><span class="h-icon <%=iconSkin%>"></span> <%=text%></span></a>',
                "TEXT": '<button id="<%=data.id%>"  <%if(data.isToggle){%>data-toggle="button"<%}%> autocomplete="off" type="button"><i class="fa <%=data.iconSkin%>"></i><%=data.text%></button>',
                "ICON": '<a id="<%=id%>" data-act="<%=id%>" class="h-btn <%=className%>" title="<%=text%>" href="javascript:void(0)"><span class="h-btn-content"><span class="h-icon <%=iconSkin%>"></span></span></a>',
                "TOOL_ICON": '<a id="<%=id%>" data-act="<%=id%>" class="h-icon <%=iconSkin%> <%=className%>" title="<%=text%>" href="javascript:void(0)" ></a>',
                "TOOLBAR": '<a id="<%=id%>" data-act="<%=id%>" class="h-btn h-btn-toolbar <%=className%>" href="javascript:void(0)"><span class="h-btn-content"><span class="h-icon <%=iconSkin%>"></span><%=text%></span></a>',
                "TABLE": '<a id="<%=id%>" data-act="<%=id%>" class="h-btn h-btn-table <%=className%>" style="display:<%=typeof(visible)==\'undefined\' || visible? \'\':\'none\'%>" href="javascript:void(0)" title="<%=text%>"><span class="h-btn-content"><span class="h-icon <%=iconSkin%>"></span></span></a>',
                "FORM": '<a id="<%=id%>" data-act="<%=id%>" class="h-btn h-btn-form <%=className%>" href="javascript:void(0)"><span class="h-btn-content"><%=text%></span></a>'
            },
            //下拉框数据项的模版
            DropDownItem: {
                "NORMAL": '<li id="<%=id%>" class=\'h-dropdown-item <%=selected ? "h-active" : "" %>\'><a data-role="<%=role%>" class="h-block" href="javascript:void(0)"><%=text%></a></li>',
                "ICON_ITEM": '<li id="<%=id%>" class=\'h-dropdown-item <%=selected ? "h-active" : "" %>\'><a data-role="<%=role%>" class="h-block" href="javascript:void(0)"><span class="h-icon <%=iconSkin%>"></span><%=text%></a></li>',
                "MENU_ITEM": '<li id="<%=id%>" class=\'h-dropdown-item <%=selected ? "h-active" : "" %>\'><a data-role="<%=role%>" class="h-block" href="javascript:void(0)"><div class="h-item-l"><span class="h-icon h-icon-xl <%=iconSkin%>"></span></div><div class="h-item-r"><strong><%=text%></strong><br><span><%=path%></span></div></a></li>',
                "CHECKBOX_ITEM": '<li id="<%=id%>" class="h-dropdown-item"><div class="h-checkbox h-pl-10"><label><input type="checkbox" name="<%=chkName%>" value="<%=id%>"><%=text%></label></div></li>',
                "NOT_FOUND": '<div class=" h-pad10 ">未找到与<span class="h-color-danger h-font-b h-ml-5 h-mr-5 h-font-12">"<%=text%>"</span>相关数据，请重新输入</div>',
                "NOT_DATA": '<div class=" h-pad10 ">暂无可选的数据</div>',
                "LOADING": '<div class=" h-pad10 "><div class="h-loading"><span class="h-icon h-icon-loading"></span><span class="h-loading-text">数据加载中...</span></div></div>'
            },

        },
        Icon: {
            ADJUST: "fa-adjust",
            ADN: "fa-adn",
            ALIGN_CENTER: "fa-align-center",
            ALIGN_JUSTIFY: "fa-align-justify",
            ALIGN_LEFT: "fa-align-left",
            AMBULANCE: "fa-ambulance",
            ANCHOR: "fa-anchor",
            ANDROID: "fa-android",
            ANGELLIST: "fa-angellist",
            ANGLE_DOUBLE_DOWN: "fa-angle-double-down",
            ANGLE_DOUBLE_LEFT: "fa-angle-double-left",
            ANGLE_DOUBLE_RIGHT: "fa-angle-double-right",
            ANGLE_DOUBLE_UP: "fa-angle-double-up",
            ANGLE_DOWN: "fa-angle-down",
            ANGLE_LEFT: "fa-angle-left",
            ANGLE_RIGHT: "fa-angle-right",
            ANGLE_UP: "fa-angle-up",
            APPLE: "fa-apple",
            ARCHIVE: "fa-archive",
            AREA_CHART: "fa-area-chart",
            ARROW_CIRCLE_DOWN: "fa-arrow-circle-down",
            ARROW_CIRCLE_LEFT: "fa-arrow-circle-left",
            ARROW_CIRCLE_O_DOWN: "fa-arrow-circle-o-down",
            ARROW_CIRCLE_O_LEFT: "fa-arrow-circle-o-left",
            ARROW_CIRCLE_O_RIGHT: "fa-arrow-circle-o-right",
            ARROW_CIRCLE_O_UP: "fa-arrow-circle-o-up",
            ARROW_CIRCLE_RIGHT: "fa-arrow-circle-right",
            ARROW_CIRCLE_UP: "fa-arrow-circle-up",
            ARROW_DOWN: "fa-arrow-down",
            ARROW_LEFT: "fa-arrow-left",
            ARROW_RIGHT: "fa-arrow-right",
            ARROW_UP: "fa-arrow-up",
            ARROWS: "fa-arrows",
            ARROWS_ALT: "fa-arrows-alt",
            ARROWS_H: "fa-arrows-h",
            ARROWS_V: "fa-arrows-v",
            ASTERISK: "fa-asterisk",
            AT: "fa-at",
            BAN: "fa-ban",
            BAR_CHART_O: "fa-bar-chart-o",
            BARCODE: "fa-barcode",
            BARS: "fa-bars",
            BEER: "fa-beer",
            BEHANCE: "fa-behance",
            BEHANCE_SQUARE: "fa-behance-square",
            BELL: "fa-bell",
            BELL_O: "fa-bell-o",
            BELL_SLASH: "fa-bell-slash",
            BELL_SLASH_O: "fa-bell-slash-o",
            BICYCLE: "fa-bicycle",
            BINOCULARS: "fa-binoculars",
            BIRTHDAY_CAKE: "fa-birthday-cake",
            BITBUCKET: "fa-bitbucket",
            BITBUCKET_SQUARE: "fa-bitbucket-square",
            BOLD: "fa-bold",
            BOLT: "fa-bolt",
            BOMB: "fa-bomb",
            BOOK: "fa-book",
            BOOKMARK: "fa-bookmark",
            BOOKMARK_O: "fa-bookmark-o",
            BRIEFCASE: "fa-briefcase",
            BTC: "fa-btc",
            BUG: "fa-bug",
            BUILDING: "fa-building",
            BUILDING_O: "fa-building-o",
            BULLHORN: "fa-bullhorn",
            BULLSEYE: "fa-bullseye",
            BUS: "fa-bus",
            CALCULATOR: "fa-calculator",
            CALENDAR: "fa-calendar",
            CALENDAR_O: "fa-calendar-o",
            CAMERA_RETRO: "fa-camera-retro",
            CAR: "fa-car",
            CARET_DOWN: "fa-caret-down",
            CARET_LEFT: "fa-caret-left",
            CARET_RIGHT: "fa-caret-right",
            CARET_SQUARE_O_DOWN : "fa-caret-square-o-down ",
            CARET_SQUARE_O_DOWN: "fa-caret-square-o-down",
            CARET_SQUARE_O_LEFT: "fa-caret-square-o-left",
            CARET_SQUARE_O_RIGHT: "fa-caret-square-o-right",
            CARET_SQUARE_O_UP: "fa-caret-square-o-up",
            CARET_UP: "fa-caret-up",
            CC: "fa-cc",
            CC_AMEX: "fa-cc-amex",
            CC_DISCOVER: "fa-cc-discover",
            CC_MASTERCARD: "fa-cc-mastercard",
            CC_STRIPE: "fa-cc-stripe",
            CC_VISA: "fa-cc-visa",
            CERTIFICATE : "fa-certificate ",
            CHAIN_BROKEN: "fa-chain-broken",
            CHECK: "fa-check",
            CHECK_CIRCLE: "fa-check-circle",
            CHECK_CIRCLE_O: "fa-check-circle-o",
            CHECK_SQUARE: "fa-check-square",
            CHECK_SQUARE_O: "fa-check-square-o",
            CHECKERED: "fa-checkered",
            CHEVRON_CIRCLE_DOWN: "fa-chevron-circle-down",
            CHEVRON_CIRCLE_LEFT: "fa-chevron-circle-left",
            CHEVRON_CIRCLE_RIGHT: "fa-chevron-circle-right",
            CHEVRON_CIRCLE_UP: "fa-chevron-circle-up",
            CHEVRON_DOWN: "fa-chevron-down",
            CHEVRON_LEFT: "fa-chevron-left",
            CHEVRON_RIGHT: "fa-chevron-right",
            CHEVRON_UP: "fa-chevron-up",
            CHILD: "fa-child",
            CIRCLE: "fa-circle",
            CIRCLE_O: "fa-circle-o",
            CIRCLE_O_NOTCH: "fa-circle-o-notch",
            CIRCLE_THIN: "fa-circle-thin",
            CLOSE: "fa-close",
            CLIPBOARD: "fa-clipboard",
            CLOCK_O: "fa-clock-o",
            CLOUD: "fa-cloud",
            CLOUD_DOWNLOAD: "fa-cloud-download",
            CLOUD_UPLOAD: "fa-cloud-upload",
            CODE: "fa-code",
            CODE_FORK: "fa-code-fork",
            CODEPEN: "fa-codepen",
            COFFEE: "fa-coffee",
            COG: "fa-cog",
            COGS: "fa-cogs",
            COMMENT: "fa-comment",
            COMMENT_O: "fa-comment-o",
            COMMENTS: "fa-comments",
            COMMENTS_O: "fa-comments-o",
            COMPASS: "fa-compass",
            COPYRIGHT: "fa-copyright",
            CREDIT_CARD: "fa-credit-card",
            CROP: "fa-crop",
            CROSSHAIRS: "fa-crosshairs",
            CSS3: "fa-css3",
            CUBE: "fa-cube",
            CUBES: "fa-cubes",
            CUTLERY: "fa-cutlery",
            DATABASE: "fa-database",
            DELICIOUS: "fa-delicious",
            DESKTOP: "fa-desktop",
            DEVIANTART: "fa-deviantart",
            DIGG: "fa-digg",
            DOT_CIRCLE_O: "fa-dot-circle-o",
            DRIBBBLE: "fa-dribbble",
            DROPBOX: "fa-dropbox",
            DRUPAL: "fa-drupal",
            ELLIPSIS_H: "fa-ellipsis-h",
            ELLIPSIS_V: "fa-ellipsis-v",
            EMPIRE: "fa-empire",
            ENVELOPE: "fa-envelope",
            ENVELOPE_SQUARE: "fa-envelope-square",
            ERASER: "fa-eraser",
            EUR: "fa-eur",
            EXCHANGE: "fa-exchange",
            EXCLAMATION: "fa-exclamation",
            EXCLAMATION_CIRCLE: "fa-exclamation-circle",
            EXCLAMATION_TRIANGLE: "fa-exclamation-triangle",
            EXTERNAL_LINK: "fa-external-link",
            EXTERNAL_LINK_SQUARE: "fa-external-link-square",
            EYE: "fa-eye",
            EYE_SLASH: "fa-eye-slash",
            EYEDROPPER: "fa-eyedropper",
            FACEBOOK: "fa-facebook",
            FACEBOOK_SQUARE: "fa-facebook-square",
            FAX: "fa-fax",
            FEMALE: "fa-female",
            FIGHTER_JET: "fa-fighter-jet",
            FILE: "fa-file",
            FILE_ARCHIVE_O: "fa-file-archive-o",
            FILE_AUDIO_O: "fa-file-audio-o",
            FILE_CODE_O: "fa-file-code-o",
            FILE_EXCEL_O: "fa-file-excel-o",
            FILE_IMAGE_O: "fa-file-image-o",
            FILE_O: "fa-file-o",
            FILE_PDF_O: "fa-file-pdf-o",
            FILE_POWERPOINT_O : "fa-file-powerpoint-o ",
            FILE_POWERPOINT_O: "fa-file-powerpoint-o",
            FILE_TEXT: "fa-file-text",
            FILE_TEXT_O: "fa-file-text-o",
            FILE_VIDEO_O: "fa-file-video-o",
            FILE_WORD_O: "fa-file-word-o",
            FILES_O: "fa-files-o",
            FILM: "fa-film",
            FILTER: "fa-filter",
            FIRE: "fa-fire",
            FIRE_EXTINGUISHER: "fa-fire-extinguisher",
            FLAG: "fa-flag",
            FLAG_O: "fa-flag-o",
            FLASK: "fa-flask",
            FLICKR: "fa-flickr",
            FLOPPY_O: "fa-floppy-o",
            FOLDER: "fa-folder",
            FOLDER_O: "fa-folder-o",
            FOLDER_OPEN: "fa-folder-open",
            FOLDER_OPEN_O : "fa-folder-open-o ",
            FONT: "fa-font",
            FOURSQUARE: "fa-foursquare",
            FROWN_O: "fa-frown-o",
            FUTBOL_O: "fa-futbol-o",
            GAMEPAD: "fa-gamepad",
            GAVEL: "fa-gavel",
            GBP: "fa-gbp",
            GIFT: "fa-gift",
            GIT: "fa-git",
            GIT_SQUARE: "fa-git-square",
            GITHUB: "fa-github",
            GITHUB_ALT: "fa-github-alt",
            GITHUB_SQUARE: "fa-github-square",
            GITTIP: "fa-gittip",
            GLASS: "fa-glass",
            GLOBE: "fa-globe",
            GOOGLE: "fa-google",
            GOOGLE_PLUS: "fa-google-plus",
            GOOGLE_PLUS_SQUARE: "fa-google-plus-square",
            GOOGLE_WALLET: "fa-google-wallet",
            GRADUATION_CAP: "fa-graduation-cap",
            H_SQUARE: "fa-h-square",
            HACKER_NEWS: "fa-hacker-news",
            HAND_O_DOWN: "fa-hand-o-down",
            HAND_O_LEFT: "fa-hand-o-left",
            HAND_O_RIGHT: "fa-hand-o-right",
            HAND_O_UP: "fa-hand-o-up",
            HDD_O: "fa-hdd-o",
            HEADER: "fa-header",
            HEADPHONES: "fa-headphones",
            HEART: "fa-heart",
            HEART_O: "fa-heart-o",
            HISTORY: "fa-history",
            HOME: "fa-home",
            HOSPITAL_O: "fa-hospital-o",
            HTML5: "fa-html5",
            ILS: "fa-ils",
            INBOX: "fa-inbox",
            INDENT: "fa-indent",
            INFO: "fa-info",
            INFO_CIRCLE: "fa-info-circle",
            INR: "fa-inr",
            INSTAGRAM: "fa-instagram",
            IOXHOST: "fa-ioxhost",
            ITALIC: "fa-italic",
            JOOMLA: "fa-joomla",
            JPY: "fa-jpy",
            JSFIDDLE: "fa-jsfiddle",
            KEY: "fa-key",
            KEYBOARD_O: "fa-keyboard-o",
            KRW: "fa-krw",
            LANGUAGE: "fa-language",
            LAPTOP: "fa-laptop",
            LASTFM: "fa-lastfm",
            LASTFM_SQUARE: "fa-lastfm-square",
            LEAF: "fa-leaf",
            LEVEL_DOWN: "fa-level-down",
            LEVEL_UP: "fa-level-up",
            LIGHTBULB_O: "fa-lightbulb-o",
            LINE_CHART: "fa-line-chart",
            LINK: "fa-link",
            LINKEDIN: "fa-linkedin",
            LINKEDIN_SQUARE: "fa-linkedin-square",
            LINUX: "fa-linux",
            LIST: "fa-list",
            LIST_ALT: "fa-list-alt",
            LIST_OL: "fa-list-ol",
            LIST_UL: "fa-list-ul",
            LOCATION_ARROW: "fa-location-arrow",
            LOCK: "fa-lock",
            LONG_ARROW_DOWN: "fa-long-arrow-down",
            LONG_ARROW_LEFT: "fa-long-arrow-left",
            LONG_ARROW_RIGHT: "fa-long-arrow-right",
            LONG_ARROW_UP: "fa-long-arrow-up",
            MAGIC: "fa-magic",
            MAGNET: "fa-magnet",
            MALE: "fa-male",
            MAP_MARKER: "fa-map-marker",
            MAXCDN: "fa-maxcdn",
            MEANPATH: "fa-meanpath",
            MEDKIT: "fa-medkit",
            MEH_O: "fa-meh-o",
            MICROPHONE: "fa-microphone",
            MICROPHONE_SLASH: "fa-microphone-slash",
            MINUS: "fa-minus",
            MINUS_CIRCLE: "fa-minus-circle",
            MINUS_SQUARE: "fa-minus-square",
            MINUS_SQUARE_O: "fa-minus-square-o",
            MOBILE: "fa-mobile",
            MONEY: "fa-money",
            MOON_O: "fa-moon-o",
            MUSIC: "fa-music",
            NEWSPAPER: "fa-newspaper",
            OPENID: "fa-openid",
            OUTDENT: "fa-outdent",
            PAGELINES: "fa-pagelines",
            PAINT_BRUSH: "fa-paint-brush",
            PAPER_PLANE: "fa-paper-plane",
            PAPER_PLANE_O: "fa-paper-plane-o",
            PAPERCLIP: "fa-paperclip",
            PARAGRAPH: "fa-paragraph",
            PAW: "fa-paw",
            PAYPAL: "fa-paypal",
            PENCIL: "fa-pencil",
            PENCIL_SQUARE: "fa-pencil-square",
            PENCIL_SQUARE_O: "fa-pencil-square-o",
            PHONE: "fa-phone",
            PHONE_SQUARE: "fa-phone-square",
            PICTURE_O: "fa-picture-o",
            PIE_CHART: "fa-pie-chart",
            PIED_PIPER: "fa-pied-piper",
            PIED_PIPER_ALT: "fa-pied-piper-alt",
            PINTEREST: "fa-pinterest",
            PINTEREST_SQUARE: "fa-pinterest-square",
            PLANE: "fa-plane",
            PLUG: "fa-plug",
            PLUS: "fa-plus",
            PLUS_CIRCLE: "fa-plus-circle",
            PLUS_SQUARE: "fa-plus-square",
            PLUS_SQUARE_O: "fa-plus-square-o",
            POWER_OFF: "fa-power-off",
            PRINT: "fa-print",
            PUZZLE_PIECE: "fa-puzzle-piece",
            QQ: "fa-qq",
            QRCODE: "fa-qrcode",
            QUESTION: "fa-question",
            QUESTION_CIRCLE: "fa-question-circle",
            QUOTE_LEFT: "fa-quote-left",
            RANDOM: "fa-random",
            REBEL: "fa-rebel",
            RECYCLE: "fa-recycle",
            REDDIT: "fa-reddit",
            REDDIT_SQUARE: "fa-reddit-square",
            REFRESH: "fa-refresh",
            RENREN: "fa-renren",
            REPEAT: "fa-repeat",
            REPLY: "fa-reply",
            REPLY_ALL: "fa-reply-all",
            RETWEET: "fa-retweet",
            ROCKET: "fa-rocket",
            RSS: "fa-rss",
            RSS_SQUARE: "fa-rss-square",
            RUB: "fa-rub",
            SAVE: "fa-save",
            SCISSORS: "fa-scissors",
            SEARCH: "fa-search",
            SEARCH_MINUS: "fa-search-minus",
            SEARCH_PLUS: "fa-search-plus",
            SHARE: "fa-share",
            SHARE_ALT: "fa-share-alt",
            SHARE_ALT_SQUARE: "fa-share-alt-square",
            SHARE_SQUARE_O: "fa-share-square-o",
            SHEKEL: "fa-shekel",
            SHEQEL: "fa-sheqel",
            SHIELD: "fa-shield",
            SHOPPING_CART: "fa-shopping-cart",
            SIGN_OUT: "fa-sign-out",
            SIGNAL: "fa-signal",
            SKYPE: "fa-skype",
            SLACK: "fa-slack",
            SLIDERS: "fa-sliders",
            SLIDESHARE: "fa-slideshare",
            SMILE_O: "fa-smile-o",
            SOCCER_BALL_O: "fa-soccer-ball-o",
            SORT: "fa-sort",
            SORT_ALPHA_ASC: "fa-sort-alpha-asc",
            SORT_ALPHA_DESC: "fa-sort-alpha-desc",
            SORT_AMOUNT_ASC: "fa-sort-amount-asc",
            SORT_AMOUNT_DESC: "fa-sort-amount-desc",
            SORT_ASC: "fa-sort-asc",
            SORT_DESC: "fa-sort-desc",
            SORT_NUMERIC_ASC: "fa-sort-numeric-asc",
            SORT_NUMERIC_DESC: "fa-sort-numeric-desc",
            SOUNDCLOUD: "fa-soundcloud",
            SPACE_SHUTTLE: "fa-space-shuttle",
            SPINNER: "fa-spinner",
            SPOON: "fa-spoon",
            SPOTIFY: "fa-spotify",
            SQUARE: "fa-square",
            SQUARE_O: "fa-square-o",
            STACK_EXCHANGE: "fa-stack-exchange",
            STACK_OVERFLOW: "fa-stack-overflow",
            STAR: "fa-star",
            STAR_HALF: "fa-star-half",
            STAR_HALF_O: "fa-star-half-o",
            STAR_O: "fa-star-o",
            STEAM: "fa-steam",
            STEAM_SQUARE: "fa-steam-square",
            STETHOSCOPE: "fa-stethoscope",
            STRIKETHROUGH: "fa-strikethrough",
            STUMBLEUPON: "fa-stumbleupon",
            STUMBLEUPON_CIRCLE: "fa-stumbleupon-circle",
            SUBSCRIPT: "fa-subscript",
            SUITCASE: "fa-suitcase",
            TABLE: "fa-table",
            TABLET: "fa-tablet",
            TACHOMETER: "fa-tachometer",
            TAG: "fa-tag",
            TAGS: "fa-tags",
            TASKS: "fa-tasks",
            TENCENT_WEIBO: "fa-tencent-weibo",
            TERMINAL: "fa-terminal",
            TEXT_HEIGHT: "fa-text-height",
            TH_LARGE: "fa-th-large",
            TH_LIST: "fa-th-list",
            THUMB_TACK: "fa-thumb-tack",
            THUMBS_DOWN: "fa-thumbs-down",
            THUMBS_O_UP: "fa-thumbs-o-up",
            THUMBS_UP: "fa-thumbs-up",
            TICKET: "fa-ticket",
            TIMES: "fa-times",
            TIMES_CIRCLE: "fa-times-circle",
            TIMES_CIRCLE_O: "fa-times-circle-o",
            TINT: "fa-tint",
            TOGGLE_OFF: "fa-toggle-off",
            TOGGLE_ON: "fa-toggle-on",
            TRASH: "fa-trash",
            TRASH_O: "fa-trash-o",
            TREE: "fa-tree",
            TRELLO: "fa-trello",
            TROPHY: "fa-trophy",
            TRUCK: "fa-truck",
            TRY: "fa-try",
            TTY: "fa-tty",
            TUMBLR: "fa-tumblr",
            TUMBLR_SQUARE: "fa-tumblr-square",
            TWITCH: "fa-twitch",
            TWITTER: "fa-twitter",
            TWITTER_SQUARE: "fa-twitter-square",
            UMBRELLA: "fa-umbrella",
            UNDERLINEALIGN_RIGHT: "fa-underlinealign-right",
            UNDO: "fa-undo",
            UNIVERSITY: "fa-university",
            UNLOCK: "fa-unlock",
            UNLOCK_ALT: "fa-unlock-alt",
            UPLOAD: "fa-upload",
            DOWNLOAD: "fa-download",
            USD: "fa-usd",
            USER: "fa-user",
            USER_MD: "fa-user-md",
            USERS: "fa-users",
            VIDEO_CAMERA: "fa-video-camera",
            VIMEO_SQUARE: "fa-vimeo-square",
            VINE: "fa-vine",
            VK: "fa-vk",
            VOLUME_DOWN: "fa-volume-down",
            VOLUME_OFF: "fa-volume-off",
            VOLUME_UP: "fa-volume-up",
            WEIBO: "fa-weibo",
            WEIXIN: "fa-weixin",
            WHEELCHAIR: "fa-wheelchair",
            WIDTH: "fa-width",
            WIFI: "fa-wifi",
            WINDOWS: "fa-windows",
            WORDPRESS: "fa-wordpress",
            WRENCH: "fa-wrench",
            XING: "fa-xing",
            XING_SQUARE: "fa-xing-square",
            YAHOO: "fa-yahoo",
            YELP: "fa-yelp",
            YOUTUBE: "fa-youtube",
            YOUTUBE_PLAY: "fa-youtube-play",
            YOUTUBE_SQUARE: "fa-youtube-square",
        },
        IconSize:{
            LG:"fa-lg",
            X2:"fa-2x",
            X3:"fa-3x",
            X4:"fa-4x",
            X5:"fa-5x",
        },
        IconRotate:{
            90:"fa-rotate-90",
            180:"fa-rotate-180",
            270:"fa-rotate-270",
            HORIZONTAL:"fa-flip-horizontal",
            VERTICAL:"fa-flip-vertical"
        },
        IconStacked:{
            CIRCLE:"fa-circle",
            SQUARE:"fa-square",
            SQUARE_O:"fa-square-o",
            BAN:"fa-ban",
        },
        //按钮图标对应的样式名
        ButtonIcon: {
            "ADD": "h-icon-add",
            "EDIT": "h-icon-edit",
            "OPERATE": "h-icon-operate",
            "DELETE": "h-icon-delete",
            "REMOVE": "h-icon-delete",
            "SEARCH": "h-icon-search",
            "VIEW": "h-icon-view",
            "COPY": "h-icon-copy",
            "PRINT": "h-icon-print",
            "DOWNLOAD": "h-icon-download",
            "UPLOAD": "h-icon-upload",
            "IMPORT": "h-icon-import",
            "EXPORT": "h-icon-export",
            "REFRESH": "h-icon-refresh",
            "RELEASE": "h-icon-send",
            "CHART": "h-icon-chart",
            "LOCK": "h-icon-lock",
            "UNLOCK": "h-icon-unlock",
            "SAVE": "h-icon-save",
            "PLAY": "h-icon-play",
            "STOP": "h-icon-stop",
            "CLOSE": "h-icon-close",
            "TAB_CLOSE": "h-icon-tab-close",
            "MORE": "h-icon-more",
            "BATCH_EDIT": "h-icon-batch-edit",
            "ONLINE_ADD": "h-icon-add",
            "ONLINE_EDIT": "h-icon-batch-edit",
            "ONLINE_DELETE": "h-icon-delete",
            "ONLINE_SUBMIT": "h-icon-confirm",

            "EXPAND": "h-icon-down",
            "COLLAPSE": "h-icon-up",
            "MAXIMIZE": "h-icon-maximize",
            "RESTORE": "h-icon-restore",

            "ASSIGN": "h-icon-assign",     //分配
            "CANCEL": "h-icon-cancel",   //作废

            "FLOW_DELETE": "h-icon-delete",     //删除
            "FLOW_ASSIGN": "h-icon-assign",     //分配
            "FLOW_APPROVE": "h-icon-confirm", //同意
            "FLOW_CANCEL": "h-icon-invalid",   //作废
            "FLOW_SIGN_IN": "h-icon-sign-in", //签收
            "FLOW_SUBMIT": "h-icon-confirm",   //同意
            "FLOW_SUSPEND": "h-icon-suspend",  //挂起
            "FLOW_RESUME": "h-icon-play",    //重新开始
            "FLOW_WITHDRAW": "h-icon-quit",  //回退
            "FLOW_REFUSE": "h-icon-refuse",     //拒绝
            "FLOW_REDO": "h-icon-back",   //重做
            "FLOW_BACK": "h-icon-back"  //退回
        },
        //键盘上按键对应的ASCII码常量
        KeyCode: {
            BACKSPACE: 8,
            COMMA: 188,       //逗号
            SEMICOLON: 186,   //分号
            COMMA_SEMICOLON: 229,  //中文下的逗号和分号
            DELETE: 46,
            DOWN: 40,
            END: 35,
            ENTER: 13,
            ESCAPE: 27,
            HOME: 36,
            LEFT: 37,
            NUMPAD_ADD: 107,
            NUMPAD_DECIMAL: 110,
            NUMPAD_DIVIDE: 111,
            NUMPAD_ENTER: 108,
            NUMPAD_MULTIPLY: 106,
            NUMPAD_SUBTRACT: 109,
            PAGE_DOWN: 34,
            PAGE_UP: 33,
            PERIOD: 190,
            RIGHT: 39,
            SPACE: 32,
            TAB: 9,
            UP: 38
        },

    };

    return CommonConstant;
});